name: "Find Latest Tag(master) of Git repository"
description: "Find latest tag of any Git repository on the Internet"
inputs:
  repo:
    description: "Repo to check the latest tag for"
    required: true
  tag:
    description: "Regular expression to match tags against"
    default: "" # empty regex matches all tags
outputs:
  tag:
    description: "Latest tag matching the regular expression"
    value: ${{ steps.flt.outputs.tag }}
runs:
  using: "composite"
  steps:
    - run: |
        actionPath="${{ github.action_path }}"
        if [[ "${{ runner.os }}" == 'Windows' ]];then
          actionPath=$(cygpath -u "${{ github.action_path }}")
        fi
        "$actionPath"/find_latest_tag.sh '${{ inputs.repo }}' '${{ inputs.tag }}'
      shell: bash
      id: flt
branding:
  icon: tag
  color: red
